language: python
dist: trusty

install:
  - pip install tox codecov

matrix:
 include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.7
    env: TOXENV=py37

script:
  - tox -e TOXENV

after_success:
  - codecov -e TOXENV
